variables:
  IMAGE_TAG: ${CI_COMMIT_TAG}
  # IMAGE_REPOSITORY está definida nas variáveis de CI/CD no GitLab

stages:
- build
- release

build:
  stage: build
  only:
  - tags
  script:
  - docker compose build --force-rm

publish:
  stage: release
  only:
  - tags
  script:
  - docker compose push
